const WHITE = '#FFFFFF';
const DARK = '#414360';
const LIGHT = WHITE;
const HELPER_TEXT_DARK = '#90EE90';
const HELPER_TEXT_LIGHT = '#00FF00';
const TAB_ACTIVE_COLOR = '#694fad';
const TAB_INACTIVE_COLOR = '#3e2465';

export {
  WHITE,
  DARK,
  LIGHT,
  HELPER_TEXT_DARK,
  HELPER_TEXT_LIGHT,
  TAB_ACTIVE_COLOR,
  TAB_INACTIVE_COLOR,
};
